compiler: clang
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- sudo add-apt-repository -y ppa:beineri/opt-qt532
- sudo add-apt-repository -y ppa:h-rayflood/llvm
- sudo add-apt-repository -y ppa:kalakris/cmake
- sudo apt-get update
- sudo dpkg -r cmake cmake-data
- sudo apt-get -y install cmake ninja-build
- sudo apt-get -y install alsa-base alsa-utils libasound2 libasound2-dev glib2.0 libglib2.0-dev
- sudo apt-get -y install qt53declarative clang-3.4
- sudo apt-get -y install pep8 pyflakes libpulse-dev
- sudo apt-get -y install qt53quickcontrols qt53graphicaleffects
- sudo apt-get -y install qt53tools
- export CXX="clang++-3.4"
script:
- source /opt/qt53/bin/qt53-env.sh
- mkdir .build
- cd .build
- cmake -G Ninja ..
- sudo ninja -j2 install

notifications:
  slack: papyros:qTNflfj4wj3AcYKLJJdpKOa4
